"""
Модуль для управления переводами интерфейса
"""

TRANSLATIONS = {
    'ru': {
        # Меню
        'menu_file': 'Файл',
        'menu_strategies': 'Стратегии',
        'menu_tools': 'Инструменты',
        'menu_settings': 'Настройки',
        'menu_open_settings': 'Настройки',
        'menu_update': 'Обновление',
        'menu_addons': 'Дополнения',
        'menu_help': 'Справка',
        'menu_change_language': 'Язык программы',
        'menu_list_strategies': 'Список всех стратегий',
        'strategies_open_winws_folder': 'Открыть папку winws',
        'menu_add_b_flag_submenu': 'Добавление команды /B',
        'menu_add_b_flag': 'Добавить /B во все стратегии',
        'menu_remove_b_flag': 'Удалить /B из всех стратегий',
        'menu_add_b_flag_on_update': 'Добавлять /B при обновлении',
        'menu_run_test': 'Тестирование',
        'menu_run_diagnostics': 'Диагностика',
        'menu_lists_editor': 'Редактор списков',
        'menu_editor': 'Редактор',
        'menu_create_bin': 'Создание bin',
        'menu_open_folder': 'Открыть папку...',
        'menu_open_winws_folder': 'Открыть папку winws',
        'menu_open_config_folder': 'Открыть папку конфигурации программы',
        'menu_minimize_to_tray': 'Свернуть окно',
        'menu_quit_app': 'Закрыть программу',
        'bin_creator_dst_label': 'Имя файла в bin:',
        'bin_creator_hex_label': 'Содержимое (hex):',
        'bin_creator_dst_placeholder': 'example.bin',
        'bin_creator_hex_placeholder': '00 ff 01 02 ...',
        'bin_creator_create_btn': 'Создать bin',
        'bin_creator_need_hex': 'Введите содержимое bin-файла (hex).',
        'bin_creator_cannot_create_dir': 'Не удалось создать папку bin:',
        'bin_creator_invalid_hex': 'Некорректный формат hex-данных.',
        'bin_creator_hex_odd': 'Количество hex-символов должно быть чётным.',
        'bin_creator_hex_parse_error': 'Ошибка разбора hex-данных:',
        'bin_creator_write_error': 'Ошибка записи файла:',
        'bin_creator_success': 'Файл успешно создан:\n{0}',
        'menu_exit': 'Выход',
        
        # Настройки
        'settings_show_tray': 'Отображать в трее',
        'settings_close_winws': 'Закрывать winws при выходе',
        'settings_start_minimized': 'Запускать свернутым в трей',
        'settings_auto_start': 'Автозапуск последней стратегии',
        'settings_autostart_windows': 'Автозапуск с Windows (с правами администратора)',
        'settings_autostart_tooltip': 'Программа запускается при входе в систему с правами администратора без запроса UAC. Для включения нужен запуск программы от имени администратора.',
        'settings_auto_restart_strategy': 'Автоперезапуск стратегии',
        'settings_game_filter': 'Game фильтр',
        'settings_ipset_filter': 'IPSet фильтр',
        'settings_search_placeholder': 'Поиск...',
        'settings_nothing_found': 'Ничего не найдено',
        'settings_ok': 'Ок',
        'settings_cancel': 'Отмена',
        'settings_category_language': 'Язык',
        'settings_category_winws_path': 'Папка winws',
        'settings_winws_path_label': 'Расположение папки winws',
        'settings_winws_path_browse': '...',
        'settings_winws_path_placeholder': 'Пусто — рядом с программой',
        'settings_category_tray': 'Трей',
        'settings_category_exit_behavior': 'Поведение при выходе',
        'settings_category_autostart': 'Автозапуск',
        'settings_category_filters': 'Фильтры',
        'settings_category_app_restart': 'Автоперезапуск приложений',
        'settings_app_restart_description': 'Укажите имена процессов (например, discord.exe), которые нужно перезапускать при запуске стратегии.',
        'settings_app_restart_column_app': 'Приложение (.exe)',
        'settings_app_restart_add': 'Добавить',
        'settings_app_restart_remove': 'Удалить',
        'settings_category_b_flag': 'Флаг /B',
        'settings_category_update': 'Обновление',
        'settings_remove_check_zapret': 'Удалять проверку обновлений zapret из стратегий',
        'settings_zapret_repo_label': 'Репозиторий zapret (GitHub)',
        'settings_zapret_repo_placeholder': 'Например: Flowseal/zapret-discord-youtube или URL',
        'settings_lang_russian': 'Русский',
        'settings_lang_english': 'English',
        'first_run_title': 'Первая настройка',
        'first_run_welcome': 'Добро пожаловать в ZapretDeskop. Выберите основные параметры — их можно изменить позже в настройках.',
        'first_run_language': 'Язык',
        'first_run_options': 'Основные опции',
        'first_run_continue': 'Продолжить',
        'settings_ipset_loaded': 'Loaded (загруженный список)',
        'settings_ipset_none': 'None (отключить)',
        'settings_ipset_any': 'Any (любой трафик)',
        'update_ipset_list': 'Обновить IPSet List',
        'update_hosts_file': 'Обновить Hosts File',
        
        # Обновление
        'update_check_app': 'Проверить обновление программы',
        'update_check_zapret': 'Проверить обновление zapret',
        'update_manual': 'Обновить стратегии в ручную (zip)',
        'update_remove_check_updates': 'Удалять проверку обновлений в winws',
        
        # Кнопки
        'button_start': 'Запустить',
        'button_stop': 'Остановить',
        
        # Сообщения
        'msg_no_bat_files': 'Нет .bat файлов',
        'msg_winws_not_found': 'Папка winws не найдена',
        'msg_minimized_to_tray': 'Окно свернуто в трей',
        'msg_minimized_to_tray_info': 'Нажмите на иконку в трее, чтобы открыть окно',
        'msg_app_minimized_to_tray': 'Приложение свернуто в трей',
        'msg_app_minimized_to_tray_info': 'Нажмите на иконку в трее, чтобы открыть окно',
        'msg_check_updates_title': 'Проверка обновлений',
        'msg_check_updates_text': 'Проверка наличия обновлений стратегий zapret...',
        'msg_check_updates_info': 'Функция проверки обновлений будет реализована позже.',
        'msg_manual_update_title': 'Обновление стратегий',
        'msg_manual_update_text': 'Обновление стратегий вручную...',
        'msg_manual_update_info': 'Функция ручного обновления будет реализована позже.',
        
        # Трей меню
        'tray_show': 'Показать окно',
        'tray_hide': 'Скрыть окно',
        'tray_minimize': 'Свернуть окно',
        'tray_change_strategy': 'Изменить стратегию',
        'tray_current_strategy': 'Текущая стратегия:',
        'tray_restart_menu': 'Перезапуск',
        'tray_restart_application': 'Перезапустить программу',
        'tray_restart_strategy': 'Перезапустить стратегию',
        'tray_program_parameters': 'Параметры программы',
        'tray_quit': 'Выход',
        
        # Test Window
        'test_window_title': 'Тестирование',
        'test_menu_strategies': 'Стратегии',
        'test_menu_view': 'Вид',
        'test_menu_export': 'Экспорт',
        'test_start_button': 'Запустить тесты',
        'test_stop_button': 'Остановить',
        'test_close_button': 'Закрыть',
        'test_strategy_label': 'Стратегия:',
        'test_all_strategies': 'Все стратегии',
        'test_auto_scroll': 'Автоскролл',
        'test_status_ready': 'Готов',
        'test_status_testing': 'Тестирование:',
        'test_status_stopping': 'Остановка тестов...',
        'test_status_finished': 'Тесты завершены',
        'test_error_title': 'Ошибка',
        'test_error_cannot_determine': 'Не удалось определить выбранную стратегию',
        'test_error_no_bat_files': 'Не найдено .bat файлов для тестирования',
        'tab_test_results': 'Результаты тестирования',
        'tab_best_strategies': 'Лучшие стратегии',
        'tab_targets': 'Цели',
        'targets_save_button': 'Сохранить',
        'targets_reload_button': 'Обновить',
        'targets_file_changed': 'Файл изменен извне. Обновить?',
        'targets_unsaved_changes': 'У вас есть несохраненные изменения. Перезагрузить файл? Несохраненные изменения будут потеряны.',
        'targets_saved': 'Файл сохранен',
        'targets_error_loading': 'Ошибка загрузки файла',
        'targets_error_saving': 'Ошибка сохранения файла',
        'lists_editor_title': 'Редактор списков',
        'lists_editor_file': 'Файл:',
        'lists_editor_menu_edit': 'Правка',
        'lists_editor_open_folder': 'Открыть папку',
        'editor_create_file': 'Создать новый файл',
        'editor_save_as': 'Сохранить как...',
        'editor_open_folder': 'Открыть папку...',
        'editor_open_file_folder': 'Открыть файл...',
        'editor_open_folder_cmd': 'Command Line',
        'editor_open_folder_ps': 'Powershell',
        'editor_find_next': 'Найти далее',
        'editor_find_prev': 'Найти ранее',
        'editor_replace': 'Заменить',
        'editor_go_to': 'Перейти',
        'editor_expand_selection': 'Расширить выделение',
        'editor_shrink_selection': 'Сузить выделение',
        'editor_copy_line_up': 'Скопировать строку вверх',
        'editor_copy_line_down': 'Скопировать строку вниз',
        'editor_move_line_up': 'Переместить строку вверх',
        'editor_move_line_down': 'Переместить строку вниз',
        'editor_duplicate_selection': 'Дублировать выделение',
        'editor_add_next_occurrence': 'Добавить следующее вхождение',
        'editor_add_prev_occurrence': 'Добавить предыдущее вхождение',
        'editor_select_all_occurrences': 'Выделить все вхождения',
        'editor_column_selection': 'Режим колоночного выделения',
        'editor_fullscreen': 'Полноэкранный режим',
        'editor_zoom_menu': 'Масштаб...',
        'editor_zoom_reset_default': 'Восстановить масштаб по умолчанию',
        'editor_convert_menu': 'Конвертировать...',
        'editor_convert_line_endings_short': 'Окончание строк',
        'editor_convert_encoding_short': 'Кодировку',
        'editor_cmd_panel_title': 'Командная строка (Windows)',
        'editor_delete_file': 'Удалить файл',
        'editor_delete_file_confirm': 'Удалить файл \"{0}\"?',
        'menu_selection': 'Выделение',
        'menu_view': 'Вид',
        'editor_menu_file': 'Файл',
        'editor_menu_selection': 'Выделение',
        'editor_save': 'Сохранить',
        'editor_reload': 'Перезагрузить',
        'editor_undo': 'Отменить',
        'editor_redo': 'Повторить',
        'editor_cut': 'Вырезать',
        'editor_copy': 'Копировать',
        'editor_paste': 'Вставить',
        'editor_select_all': 'Выделить всё',
        'editor_go_to_line': 'Перейти к Строке/Столбцу',
        'editor_delete': 'Удалить',
        'editor_duplicate_line': 'Дублировать строку',
        'editor_comment': 'Закомментировать',
        'editor_uncomment': 'Раскомментировать',
        'editor_find': 'Найти',
        'editor_autocomplete': 'Автодополнение',
        'editor_close': 'Закрыть',
        'editor_word_wrap': 'Перенос строк',
        'editor_zoom_in': 'Увеличить',
        'editor_zoom_out': 'Уменьшить',
        'editor_zoom_reset': 'Сбросить масштаб',
        'editor_format_document': 'Форматировать документ',
        'editor_convert_line_endings': 'Конвертировать окончания строк',
        'editor_convert_encoding': 'Конвертировать кодировку',
        'editor_about': 'О программе',
        'menu_etcdrivers_editor': 'Редактор drivers\\etc',
        'etcdrivers_editor_title': 'Редактор drivers\\etc',
        'etcdrivers_open_folder': 'Открыть папку',
        'etcdrivers_folder_not_found': 'Папка drivers\\etc не найдена',
        'etcdrivers_save_admin_required': 'Требуются права администратора для сохранения файлов в системную папку.',
        'editor_line_column': 'Строка {0}, Столбец {1}',
        'editor_file_modified': '(изменен)',
        'editor_window_title': 'Редактор',
        'editor_tab_lists': 'Списки',
        'editor_tab_etc': 'Файл hosts',
        'editor_tab_bat': 'Стратегии',
        'find_replace_title': 'Поиск и замена',
        'find_search': 'Поиск:',
        'find_search_placeholder': 'Текст для поиска...',
        'find_replace_label': 'Заменить на:',
        'find_replace_placeholder': 'Новый текст...',
        'find_case': 'Регистр',
        'find_whole': 'Слово целиком',
        'find_next': 'Далее',
        'find_prev': 'Назад',
        'find_replace_btn': 'Заменить',
        'find_replace_all': 'Заменить всё',
        'find_not_found': 'Ничего не найдено',
        'find_replace_done': 'Замена выполнена',
        'find_replace_count': 'Заменено: {0}',
        'find_in_files_title': 'Поиск в файлах',
        'find_in_files_search': 'Поиск:',
        'find_in_files_search_btn': 'Найти',
        'find_in_files_searching': 'Поиск...',
        'find_in_files_results': 'Найдено: {0}',
        'find_in_files_no_scope': 'Нет открытой вкладки редактора',
        'country_blocklist_title': 'Список по стране',
        'country_blocklist_btn': 'Создать по стране',
        'country_blocklist_description': 'Создать список заблокированных доменов на основе данных OONI для выбранной страны.',
        'country_blocklist_country': 'Страна:',
        'country_blocklist_filename': 'Имя файла:',
        'country_blocklist_confirmed': 'Только подтверждённые блокировки (выше качество)',
        'country_blocklist_limit': 'Лимит доменов:',
        'country_blocklist_domains': 'шт.',
        'country_blocklist_create': 'Создать',
        'country_blocklist_fetching': 'Загрузка данных OONI...',
        'country_blocklist_error': 'Ошибка: {0}',
        'country_blocklist_empty': 'Данные не найдены',
        'country_blocklist_success': 'Сохранено {0} доменов в {1}',
        'country_blocklist_success_msg': 'Создан список из {0} доменов.\nФайл: {1}',
        'country_blocklist_save_error': 'Ошибка сохранения: {0}',
        'table_col_strategy': 'Стратегия',
        'table_col_target': 'Цель',
        'table_col_http_tls': 'HTTP/TLS',
        'table_col_ping': 'Ping',
        'best_strategies_col_rank': 'Место',
        'best_strategies_col_strategy': 'Стратегия',
        'best_strategies_col_http_ok': 'HTTP OK',
        'best_strategies_col_tls_ok': 'TLS OK',
        'best_strategies_col_ping_ok': 'Ping OK',
        
        # Справка
        'help_open_github': 'Открыть ZapretDeskop Github',
        'help_open_github_zapret': 'Открыть {owner} zapret Github',
        
        # Права администратора
        'admin_required_title': 'Требуются права администратора',
        'admin_required_text': 'Для работы программы требуются права администратора.\n\nПерезапустить программу с правами администратора?',
        'admin_error_title': 'Ошибка',
        'admin_error_text': 'Не удалось запросить права администратора:\n{0}\n\nПожалуйста, запустите программу от имени администратора вручную.',
        
        # Обновления
        'update_checking': 'Проверка обновлений...',
        'update_checking_app': 'Проверка обновлений программы...',
        'update_not_found': 'Обновления не найдены',
        'update_current_version': 'Установлена актуальная версия: {0}',
        'update_available_title': 'Обновление доступно',
        'update_available_text': 'Найдена новая версия: {0}\nТекущая версия: {1}\n\nХотите обновить стратегии zapret?',
        'update_available_text_app': 'Найдена новая версия программы: {0}\nТекущая версия: {1}\n\nХотите обновить программу ZapretDeskop?',
        'update_error_title': 'Ошибка',
        'update_error_url_not_found': 'URL для скачивания не найден',
        'update_stopping_winws': 'Остановка winws',
        'update_winws_running': 'Обнаружен запущенный процесс winws.exe',
        'update_winws_stop_required': 'Необходимо остановить процесс перед обновлением. Остановить сейчас?',
        'update_title': 'Обновление',
        'update_downloading': 'Скачивание обновления...',
        'update_installing': 'Установка обновления...',
        'update_completed': 'Обновление завершено',
        'update_completed_text': 'Стратегии zapret успешно обновлены до версии {0}',
        'update_completed_text_app': 'Программа ZapretDeskop успешно обновлена до версии {0}',
        'update_restart_required': 'Программа будет перезапущена автоматически',
        'update_error_title': 'Ошибка обновления',
        'update_error_text': 'Ошибка при обновлении: {0}',
        'update_manual_title': 'Обновление стратегий',
        'update_manual_select_archive': 'Выберите архив для обновления',
        'update_manual_extracting': 'Распаковка архива...',
        'update_manual_completed': 'Стратегии успешно обновлены из архива',
        'addons_title': 'Дополнения',
        'addons_description': 'Ссылки на репозитории или релизы GitHub для скачивания списков и стратегий.',
        'addons_col_name': 'Название',
        'addons_col_url': 'Ссылка (репозиторий или релиз)',
        'addons_download': 'Скачать',
        'addons_open_link': 'Открыть',
        'addons_add': 'Добавить',
        'addons_remove': 'Удалить',
        'addons_save': 'Сохранить',
        'addons_error_download': 'Ошибка при скачивании: {0}',
        'addons_error_no_zip': 'В релизе не найден zip-архив',
        'addons_success': 'Дополнение успешно установлено',
        'addons_mode_label': 'Режим установки',
        'addons_mode_full': 'Полная установка',
        'addons_mode_lists': 'Установка списков (lists)',
        'addons_mode_strategies': 'Установка стратегий (winws)',
        'addons_mode_bin': 'Установка бинарников (bin)',
        'addons_search_placeholder': 'Поиск по названию или ссылке...',
        'addons_nothing_found': 'Ничего не найдено',
        
        # Общие для диалогов
        'msg_error': 'Ошибка',
        'msg_information': 'Информация',
        'msg_result': 'Результат',
        'menu_create_strategy': 'Создать стратегию',
        'msg_autostart_enable_failed': 'Не удалось включить автозапуск',
        'msg_autostart_disable_failed': 'Не удалось выключить автозапуск',
        'msg_backup_not_found': 'Резервная копия не найдена. Обновите список IPSet из меню обновлений.',
        'msg_backup_not_found_short': 'Резервная копия не найдена. Обновите список из меню обновлений сначала.',
        'msg_add_b_flag_title': 'Добавить /B флаг',
        'msg_add_b_flag_text': 'Будет обработано файлов: {0}\n\nВо всех .bat файлах будет найдена строка:\n{1}\nИ заменена на:\n{2}\nПродолжить?',
        'msg_remove_b_flag_title': 'Удалить /B флаг',
        'msg_remove_b_flag_text': 'Будет обработано файлов: {0}\n\nВо всех .bat файлах будет найдена строка:\n{1}\nИ заменена на:\n{2}\nПродолжить?',
        'msg_processed_count': 'Обработано файлов: {0}\nИзменено файлов: {1}',
        'msg_errors_section': 'Ошибки:\n',
        'export_menu_title': 'Экспорт',
        'export_no_data': 'Нет данных для экспорта.',
        'export_table_empty': 'Таблица пуста. Нечего экспортировать.',
        'export_column': 'Колонка {0}',
        'export_success': 'Данные успешно экспортированы в:\n{0}',
        'export_error_title': 'Ошибка экспорта',
        'export_error': 'Ошибка при экспорте данных:\n{0}',
        'msg_no_bat_to_process': 'Не найдено .bat файлов для обработки',
        'msg_no_strategy_selected': 'Не выбрана стратегия для запуска',
        'update_ipset_progress': 'Обновление ipset-all...',
        'update_ipset_success': 'IPSet List успешно обновлен.',
        'update_ipset_error': 'Ошибка при обновлении IPSet List: {0}',
        'update_hosts_progress': 'Проверка hosts файла...',
        'update_hosts_needs_update': 'Hosts файл требует обновления. Пожалуйста, вручную скопируйте содержимое из открытого файла в ваш hosts файл.',
        'update_hosts_up_to_date': 'Hosts файл актуален.',
        'update_hosts_error': 'Ошибка при обновлении Hosts File: {0}',
        'update_hosts_download_failed': 'Не удалось скачать hosts файл из репозитория',
        'update_hosts_file_empty': 'Скачанный файл пуст',
        'msg_game_filter_restart': 'Game Filter {0}. Перезапустите zapret для применения изменений.',
        'msg_game_filter_toggle_error': 'Ошибка при переключении Game Filter: {0}',
        'msg_ipset_filter_restart': 'IPSet фильтр переключен в режим {0}. Перезапустите zapret для применения изменений.',
        'msg_ipset_filter_toggle_error': 'Ошибка при переключении IPSet Filter: {0}',
        'msg_game_filter_enabled': 'включен',
        'msg_game_filter_disabled': 'отключен',
        
        # Создатель стратегий
        'create_strategy_title': 'Создать стратегию',
        'create_strategy_name_label': 'Название стратегии:',
        'create_strategy_placeholder': 'general (CUSTOM)',
        'create_strategy_use_game_filter': 'Использовать Game Filter',
        'create_strategy_traffic_filters': 'Фильтры трафика',
        'create_strategy_tcp_ports': 'TCP порты:',
        'create_strategy_udp_ports': 'UDP порты:',
        'create_strategy_l7_protocols': 'L7 протоколы:',
        'create_strategy_l3_protocols': 'L3 протоколы:',
        'create_strategy_tab_filters': 'Фильтры',
        'create_strategy_domain_lists': 'Списки доменов',
        'create_strategy_hostlist': 'Hostlist:',
        'create_strategy_hostlist_exclude': 'Hostlist exclude:',
        'create_strategy_hostlist_domains': 'Hostlist domains:',
        'create_strategy_tab_lists': 'Списки',
        'create_strategy_ipset_lists': 'IPSet списки',
        'create_strategy_ipset': 'IPSet:',
        'create_strategy_ipset_exclude': 'IPSet exclude:',
        'create_strategy_dpi_methods': 'DPI Desync методы',
        'create_strategy_dpi_desync': 'DPI Desync:',
        'create_strategy_repeats': 'Repeats:',
        'create_strategy_fake_quic': 'Fake QUIC:',
        'create_strategy_fake_tls': 'Fake TLS:',
        'create_strategy_fake_tls_mod': 'Fake TLS mod:',
        'create_strategy_fake_tls_placeholder': 'none или rnd,sni=www.google.com',
        'create_strategy_fooling': 'Fooling:',
        'create_strategy_split_seqovl': 'Split seqovl:',
        'create_strategy_split_pos': 'Split pos:',
        'create_strategy_split_pattern': 'Split pattern:',
        'create_strategy_autottl': 'AutoTTL:',
        'create_strategy_any_protocol': 'Any protocol:',
        'create_strategy_fake_unknown_udp': 'Fake unknown UDP:',
        'create_strategy_cutoff': 'Cutoff:',
        'create_strategy_tab_dpi': 'DPI Desync',
        'create_strategy_extra_params': 'Дополнительные параметры',
        'create_strategy_ip_id': 'IP ID:',
        'create_strategy_tab_extra': 'Дополнительно',
        'create_strategy_btn': 'Создать файл',
        'msg_enter_strategy_name': 'Введите название стратегии',
        'msg_fill_rule_field': 'Заполните хотя бы одно поле правила',
        'msg_confirm': 'Подтверждение',
        'msg_confirm_overwrite': 'Стратегия "{0}" уже существует. Перезаписать?',
        'msg_success': 'Успех',
        'msg_strategy_created': 'Стратегия "{0}" успешно создана',
        'msg_error_creating': 'Ошибка при создании стратегии: {0}',
        'msg_file_not_found': 'Файл {0} не найден по пути: {1}',
        'msg_error_on_start': 'Ошибка при запуске: {0}',
        'msg_error_on_stop': 'Ошибка при остановке процесса: {0}',
        'msg_error_launch_title': 'Ошибка запуска',
        'msg_winws_not_started': 'Стратегия "{0}" не запустилась.\nПроцесс winws.exe не появился в течение 5 секунд.\n\nВозможно, стратегия не работает или требует дополнительной настройки.',
        'msg_bat_path_not_allowed': 'Запуск разрешён только для .bat файлов из папки winws.',
        'msg_bat_not_in_list': 'Стратегия "{0}" не в списке разрешённых. Обновите список стратегий.',
        
        # Диагностика
        'diag_running': 'Запуск диагностики...',
        'diag_completed': 'Диагностика завершена.',
        'export_txt': 'Экспорт в TXT',
        'export_csv': 'Экспорт в CSV',
        'export_json': 'Экспорт в JSON',
        'diag_bfe_passed': 'Проверка Base Filtering Engine пройдена',
        'diag_bfe_failed': '[X] Base Filtering Engine не запущен. Эта служба необходима для работы zapret',
        'diag_error_bfe': 'Ошибка проверки BFE: {0}',
        'diag_proxy_enabled': '[?] Системный прокси включен: {0}',
        'diag_proxy_check_proxy': 'Убедитесь, что прокси настроен правильно, или отключите его, если не используете',
        'diag_proxy_passed': 'Проверка прокси пройдена',
        'diag_error_proxy': 'Ошибка проверки прокси: {0}',
        'diag_tcp_passed': 'Проверка TCP timestamps пройдена',
        'diag_tcp_disabled': '[?] TCP timestamps отключены. Включение...',
        'diag_tcp_enabled': 'TCP timestamps успешно включены',
        'diag_tcp_failed': '[X] Не удалось включить TCP timestamps',
        'diag_error_tcp': 'Ошибка проверки TCP timestamps: {0}',
        'diag_adguard_found': '[X] Найден процесс Adguard. Adguard может вызывать проблемы с Discord',
        'diag_adguard_passed': 'Проверка Adguard пройдена',
        'diag_killer_found': '[X] Найдены службы Killer. Killer конфликтует с zapret',
        'diag_killer_passed': 'Проверка Killer пройдена',
        'diag_error_killer': 'Ошибка проверки служб Killer: {0}',
        'diag_intel_found': '[X] Найдена служба Intel Connectivity Network Service. Она конфликтует с zapret',
        'diag_intel_passed': 'Проверка Intel Connectivity пройдена',
        'diag_error_intel': 'Ошибка проверки Intel Connectivity: {0}',
        'diag_checkpoint_found': '[X] Найдены службы Check Point. Check Point конфликтует с zapret',
        'diag_checkpoint_uninstall': 'Попробуйте удалить Check Point',
        'diag_checkpoint_passed': 'Проверка Check Point пройдена',
        'diag_error_checkpoint': 'Ошибка проверки Check Point: {0}',
        'diag_smartbyte_found': '[X] Найдены службы SmartByte. SmartByte конфликтует с zapret',
        'diag_smartbyte_uninstall': 'Попробуйте удалить или отключить SmartByte через services.msc',
        'diag_smartbyte_passed': 'Проверка SmartByte пройдена',
        'diag_error_smartbyte': 'Ошибка проверки SmartByte: {0}',
        'diag_windivert_not_found': 'Файл WinDivert64.sys НЕ найден.',
        'diag_windivert_found': 'Файл WinDivert64.sys найден: {0}',
        'diag_error_windivert': 'Ошибка проверки WinDivert64.sys: {0}',
        'diag_vpn_found': '[?] Найдены VPN-службы: {0}. Некоторые VPN могут конфликтовать с zapret',
        'diag_vpn_disable': 'Убедитесь, что все VPN отключены',
        'diag_vpn_passed': 'Проверка VPN пройдена',
        'diag_error_vpn': 'Ошибка проверки VPN-служб: {0}',
        'diag_dns_configure': '[?] Убедитесь, что вы настроили защищённый DNS в браузере с нестандартным провайдером DNS',
        'diag_dns_win11': 'В Windows 11 вы можете настроить шифрованный DNS в Параметрах, чтобы скрыть это предупреждение',
        'diag_secure_dns_passed': 'Проверка защищённого DNS пройдена',
        'diag_dns_unknown': '[?] Не удалось проверить конфигурацию защищённого DNS',
        'diag_windivert_attempt': '[?] winws.exe не запущен, но служба WinDivert активна. Попытка удаления WinDivert...',
        'diag_windivert_removed': 'WinDivert успешно удалён',
        'diag_windivert_delete_failed': '[X] Не удалось удалить WinDivert. Проверьте вручную, не использует ли другой bypass WinDivert.',
        'diag_windivert_error': '[X] Ошибка при удалении WinDivert: {0}',
        'diag_windivert_conflict_passed': 'Проверка конфликта WinDivert пройдена',
        'diag_error_windivert_conflict': 'Ошибка проверки конфликта WinDivert: {0}',
        'diag_zapret_running': 'Служба Zapret запущена',
        'diag_zapret_strategy': 'Стратегия службы: {0}',
        'diag_zapret_stopped': '[?] Служба Zapret установлена, но не запущена',
        'diag_zapret_unknown': '[?] Статус службы Zapret неизвестен',
        'diag_zapret_not_installed': '[?] Служба Zapret не установлена',
        'diag_error_zapret': 'Ошибка проверки службы zapret: {0}',
        'diag_winws_running': 'winws.exe запущен (PID: {0})',
        'diag_winws_not_running': '[?] winws.exe не запущен',
        'diag_error_winws': 'Ошибка проверки winws.exe: {0}',
        'diag_windows_version': 'Windows {0} (Build {1}, {2})',
        'diag_error_windows': 'Ошибка проверки версии Windows: {0}',
        'diag_admin_yes': 'Запущено с правами администратора',
        'diag_admin_no': '[X] Запущено без прав администратора. Некоторые функции могут не работать',
        'diag_error_admin': 'Ошибка проверки прав администратора: {0}',
        'diag_strategies_found': 'Найдено файлов стратегий: {0}',
        'diag_strategies_empty': '[?] Файлы стратегий не найдены в папке strategies',
        'diag_strategies_not_found': '[?] Папка strategies не найдена',
        'diag_error_strategies': 'Ошибка проверки стратегий: {0}',
        'diag_dns_servers': 'Настроены DNS-серверы: {0}',
        'diag_dns_not_detected': '[?] Не удалось определить DNS-серверы',
        'diag_error_dns': 'Ошибка проверки DNS-серверов: {0}',
        'diag_adapters_found': 'Найдено сетевых адаптеров: {0}',
        'diag_adapters_not_detected': '[?] Не удалось определить сетевые адаптеры',
        'diag_error_adapters': 'Ошибка проверки сетевых адаптеров: {0}',
        'diag_targets_found': 'targets.txt найден с {0} целями',
        'diag_targets_not_found': '[?] targets.txt не найден',
        'diag_error_targets': 'Ошибка проверки targets.txt: {0}',
        'diag_hosts_found': 'Файл hosts найден с {0} записей',
        'diag_hosts_not_found': '[X] Файл hosts не найден',
        'diag_error_hosts': 'Ошибка проверки файла hosts: {0}',
        # Ссылки / контекстное меню
        'link_open_release': 'Открыть релиз версии',
        'link_copy_release': 'Копировать ссылку на релиз',
        'link_send_email': 'Написать письмо',
        'link_copy_email': 'Скопировать e-mail',
    },
    'en': {
        # Меню
        'menu_file': 'File',
        'menu_strategies': 'Strategies',
        'menu_tools': 'Tools',
        'menu_settings': 'Settings',
        'menu_open_settings': 'Settings',
        'menu_update': 'Update',
        'menu_addons': 'Add-ons',
        'menu_help': 'Help',
        'menu_change_language': 'Program language',
        'menu_list_strategies': 'List of all strategies',
        'strategies_open_winws_folder': 'Open winws folder',
        'menu_add_b_flag_submenu': 'Adding /B command',
        'menu_add_b_flag': 'Add /B to all strategies',
        'menu_remove_b_flag': 'Remove /B from all strategies',
        'menu_add_b_flag_on_update': 'Add /B on update',
        'menu_run_test': 'Run Testing',
        'menu_run_diagnostics': 'Run Diagnostics',
        'menu_lists_editor': 'Lists Editor',
        'menu_editor': 'Editor',
        'menu_create_bin': 'Create bin',
        'menu_open_folder': 'Open folder...',
        'menu_open_winws_folder': 'Open winws folder',
        'menu_open_config_folder': 'Open config folder',
        'menu_minimize_to_tray': 'Minimize window',
        'menu_quit_app': 'Quit application',
        'bin_creator_dst_label': 'File name in bin:',
        'bin_creator_hex_label': 'Content (hex):',
        'bin_creator_dst_placeholder': 'example.bin',
        'bin_creator_hex_placeholder': '00 ff 01 02 ...',
        'bin_creator_create_btn': 'Create bin',
        'bin_creator_need_hex': 'Enter bin file content (hex).',
        'bin_creator_cannot_create_dir': 'Failed to create bin folder:',
        'bin_creator_invalid_hex': 'Invalid hex format.',
        'bin_creator_hex_odd': 'Number of hex characters must be even.',
        'bin_creator_hex_parse_error': 'Hex parse error:',
        'bin_creator_write_error': 'File write error:',
        'bin_creator_success': 'File successfully created:\n{0}',
        'menu_exit': 'Exit',
        
        # Настройки
        'settings_show_tray': 'Show in tray',
        'settings_close_winws': 'Close winws on exit',
        'settings_start_minimized': 'Start minimized to tray',
        'settings_auto_start': 'Auto-start last strategy',
        'settings_autostart_windows': 'Start with Windows (as administrator)',
        'settings_autostart_tooltip': 'Program starts at logon with admin rights without UAC prompt. Requires running the program as administrator to enable.',
        'settings_auto_restart_strategy': 'Auto-restart strategy',
        'settings_game_filter': 'Game Filter',
        'settings_ipset_filter': 'IPSet Filter',
        'settings_search_placeholder': 'Search...',
        'settings_nothing_found': 'Nothing found',
        'settings_ok': 'Ok',
        'settings_cancel': 'Cancel',
        'settings_category_language': 'Language',
        'settings_category_winws_path': 'winws folder',
        'settings_winws_path_label': 'winws folder location',
        'settings_winws_path_browse': '...',
        'settings_winws_path_placeholder': 'Empty — next to program',
        'settings_category_tray': 'Tray',
        'settings_category_exit_behavior': 'Exit Behavior',
        'settings_category_autostart': 'Autostart',
        'settings_category_filters': 'Filters',
        'settings_category_app_restart': 'Auto-restart applications',
        'settings_app_restart_description': 'Specify process names (e.g. discord.exe) to restart when starting a strategy.',
        'settings_app_restart_column_app': 'Application (.exe)',
        'settings_app_restart_add': 'Add',
        'settings_app_restart_remove': 'Remove',
        'settings_category_b_flag': '/B Flag',
        'settings_category_update': 'Update',
        'settings_remove_check_zapret': 'Remove zapret update check from strategies',
        'settings_zapret_repo_label': 'zapret repository (GitHub)',
        'settings_zapret_repo_placeholder': 'e.g. Flowseal/zapret-discord-youtube or URL',
        # Links / context menu
        'link_open_release': 'Open release page',
        'link_copy_release': 'Copy release link',
        'link_send_email': 'Send email',
        'link_copy_email': 'Copy e-mail',
        'settings_lang_russian': 'Russian',
        'settings_lang_english': 'English',
        'first_run_title': 'First-time setup',
        'first_run_welcome': 'Welcome to ZapretDeskop. Choose basic options — you can change them later in Settings.',
        'first_run_language': 'Language',
        'first_run_options': 'Basic options',
        'first_run_continue': 'Continue',
        'settings_ipset_loaded': 'Loaded',
        'settings_ipset_none': 'None',
        'settings_ipset_any': 'Any',
        'update_ipset_list': 'Update IPSet List',
        'update_hosts_file': 'Update Hosts File',
        
        # Обновление
        'update_check_app': 'Check for program updates',
        'update_check_zapret': 'Check for zapret updates',
        'update_manual': 'Update strategies manually (zip)',
        'update_remove_check_updates': 'Remove check updates in winws',
        
        # Кнопки
        'button_start': 'Start',
        'button_stop': 'Stop',
        
        # Сообщения
        'msg_no_bat_files': 'No .bat files',
        'msg_winws_not_found': 'winws folder not found',
        'msg_minimized_to_tray': 'Window minimized to tray',
        'msg_minimized_to_tray_info': 'Click on the tray icon to open the window',
        'msg_app_minimized_to_tray': 'Application minimized to tray',
        'msg_app_minimized_to_tray_info': 'Click on the tray icon to open the window',
        'msg_check_updates_title': 'Check for updates',
        'msg_check_updates_text': 'Checking for zapret strategy updates...',
        'msg_check_updates_info': 'Update check function will be implemented later.',
        'msg_manual_update_title': 'Update strategies',
        'msg_manual_update_text': 'Updating strategies manually...',
        'msg_manual_update_info': 'Manual update function will be implemented later.',
        
        # Трей меню
        'tray_show': 'Show window',
        'tray_hide': 'Hide window',
        'tray_minimize': 'Minimize window',
        'tray_change_strategy': 'Change strategy',
        'tray_current_strategy': 'Current strategy:',
        'tray_restart_menu': 'Restart',
        'tray_restart_application': 'Restart application',
        'tray_restart_strategy': 'Restart strategy',
        'tray_program_parameters': 'Program Parameters',
        'tray_quit': 'Quit',
        
        # Test Window
        'test_window_title': 'Testing',
        'test_menu_strategies': 'Strategies',
        'test_menu_view': 'View',
        'test_menu_export': 'Export',
        'test_start_button': 'Start Tests',
        'test_stop_button': 'Stop',
        'test_close_button': 'Close',
        'test_strategy_label': 'Strategy:',
        'test_all_strategies': 'All strategies',
        'test_auto_scroll': 'Auto-scroll',
        'test_status_ready': 'Ready to start tests',
        'test_status_testing': 'Testing:',
        'test_status_stopping': 'Stopping tests...',
        'test_status_finished': 'Tests completed',
        'test_error_title': 'Error',
        'test_error_cannot_determine': 'Could not determine selected strategy',
        'test_error_no_bat_files': 'No .bat files found for testing',
        'tab_test_results': 'Test Results',
        'tab_best_strategies': 'Best Strategies',
        'tab_targets': 'Targets',
        'lists_editor_title': 'Lists Editor',
        'lists_editor_file': 'File:',
        'lists_editor_menu_edit': 'Edit',
        'lists_editor_open_folder': 'Open folder',
        'editor_create_file': 'Create new file',
        'editor_save_as': 'Save as...',
        'editor_open_folder': 'Open folder...',
        'editor_open_file_folder': 'Open file...',
        'editor_open_folder_cmd': 'Command Line',
        'editor_open_folder_ps': 'Powershell',
        'editor_find_next': 'Find Next',
        'editor_find_prev': 'Find Previous',
        'editor_replace': 'Replace',
        'editor_go_to': 'Go to',
        'editor_expand_selection': 'Expand Selection',
        'editor_shrink_selection': 'Shrink Selection',
        'editor_copy_line_up': 'Copy Line Up',
        'editor_copy_line_down': 'Copy Line Down',
        'editor_move_line_up': 'Move Line Up',
        'editor_move_line_down': 'Move Line Down',
        'editor_duplicate_selection': 'Duplicate Selection',
        'editor_add_next_occurrence': 'Add Next Occurrence',
        'editor_add_prev_occurrence': 'Add Previous Occurrence',
        'editor_select_all_occurrences': 'Select All Occurrences',
        'editor_column_selection': 'Column Selection Mode',
        'editor_fullscreen': 'Fullscreen mode',
        'editor_zoom_menu': 'Zoom...',
        'editor_zoom_reset_default': 'Reset zoom to default',
        'editor_convert_menu': 'Convert...',
        'editor_convert_line_endings_short': 'Line endings',
        'editor_convert_encoding_short': 'Encoding',
        'editor_cmd_panel_title': 'Command Line (Windows)',
        'editor_delete_file': 'Delete file',
        'editor_delete_file_confirm': 'Delete file \"{0}\"?',
        'menu_selection': 'Selection',
        'menu_view': 'View',
        'editor_menu_file': 'File',
        'editor_menu_selection': 'Selection',
        'editor_save': 'Save',
        'editor_reload': 'Reload',
        'editor_undo': 'Undo',
        'editor_redo': 'Redo',
        'editor_cut': 'Cut',
        'editor_copy': 'Copy',
        'editor_paste': 'Paste',
        'editor_select_all': 'Select All',
        'editor_go_to_line': 'Go to Line/Column',
        'editor_delete': 'Delete',
        'editor_duplicate_line': 'Duplicate Line',
        'editor_comment': 'Comment',
        'editor_uncomment': 'Uncomment',
        'editor_find': 'Find',
        'editor_autocomplete': 'Autocomplete',
        'editor_close': 'Close',
        'editor_word_wrap': 'Word Wrap',
        'editor_zoom_in': 'Zoom In',
        'editor_zoom_out': 'Zoom Out',
        'editor_zoom_reset': 'Reset Zoom',
        'editor_format_document': 'Format Document',
        'editor_convert_line_endings': 'Convert Line Endings',
        'editor_convert_encoding': 'Convert Encoding',
        'editor_about': 'About',
        'editor_bat_files_title': 'Strategies (.bat)',
        'menu_etcdrivers_editor': 'drivers\\etc Editor',
        'etcdrivers_editor_title': 'drivers\\etc Editor',
        'etcdrivers_open_folder': 'Open folder',
        'etcdrivers_folder_not_found': 'drivers\\etc folder not found',
        'etcdrivers_save_admin_required': 'Administrator rights required to save files in the system folder.',
        'editor_line_column': 'Line {0}, Column {1}',
        'editor_file_modified': '(modified)',
        'editor_window_title': 'Editor',
        'editor_tab_lists': 'Lists',
        'editor_tab_etc': 'File Hosts',
        'editor_tab_bat': 'Strategies',
        'find_replace_title': 'Find and Replace',
        'find_search': 'Search:',
        'find_search_placeholder': 'Text to find...',
        'find_replace_label': 'Replace with:',
        'find_replace_placeholder': 'New text...',
        'find_case': 'Case sensitive',
        'find_whole': 'Whole words',
        'find_next': 'Next',
        'find_prev': 'Previous',
        'find_replace_btn': 'Replace',
        'find_replace_all': 'Replace All',
        'find_not_found': 'Not found',
        'find_replace_done': 'Replaced',
        'find_replace_count': 'Replaced: {0}',
        'find_in_files_title': 'Find in Files',
        'find_in_files_search': 'Search:',
        'find_in_files_search_btn': 'Find',
        'find_in_files_searching': 'Searching...',
        'find_in_files_results': 'Found: {0}',
        'find_in_files_no_scope': 'No editor tab open',
        'country_blocklist_title': 'Country Blocklist',
        'country_blocklist_btn': 'Create by country',
        'country_blocklist_description': 'Create a list of blocked domains based on OONI data for the selected country.',
        'country_blocklist_country': 'Country:',
        'country_blocklist_filename': 'Filename:',
        'country_blocklist_confirmed': 'Confirmed blockings only (higher quality)',
        'country_blocklist_limit': 'Domain limit:',
        'country_blocklist_domains': 'domains',
        'country_blocklist_create': 'Create',
        'country_blocklist_fetching': 'Fetching OONI data...',
        'country_blocklist_error': 'Error: {0}',
        'country_blocklist_empty': 'No data found',
        'country_blocklist_success': 'Saved {0} domains to {1}',
        'country_blocklist_success_msg': 'Created list of {0} domains.\nFile: {1}',
        'country_blocklist_save_error': 'Save error: {0}',
        'targets_save_button': 'Save',
        'targets_reload_button': 'Reload',
        'targets_file_changed': 'File changed externally. Reload?',
        'targets_unsaved_changes': 'You have unsaved changes. Reload file? Unsaved changes will be lost.',
        'targets_saved': 'File saved',
        'targets_error_loading': 'Error loading file',
        'targets_error_saving': 'Error saving file',
        'table_col_strategy': 'Strategy',
        'table_col_target': 'Target',
        'table_col_http_tls': 'HTTP/TLS',
        'table_col_ping': 'Ping',
        'best_strategies_col_rank': 'Rank',
        'best_strategies_col_strategy': 'Strategy',
        'best_strategies_col_http_ok': 'HTTP OK',
        'best_strategies_col_tls_ok': 'TLS OK',
        'best_strategies_col_ping_ok': 'Ping OK',
        
        # Help
        'help_open_github': 'Open ZapretDeskop Github',
        'help_open_github_zapret': 'Open {owner} zapret Github',
        
        # Admin rights
        'admin_required_title': 'Administrator rights required',
        'admin_required_text': 'The program requires administrator rights to work.\n\nRestart the program with administrator rights?',
        'admin_error_title': 'Error',
        'admin_error_text': 'Failed to request administrator rights:\n{0}\n\nPlease run the program as administrator manually.',
        
        # Updates
        'update_checking': 'Checking for updates...',
        'update_checking_app': 'Checking for program updates...',
        'update_not_found': 'No updates found',
        'update_current_version': 'Current version installed: {0}',
        'update_available_title': 'Update available',
        'update_available_text': 'New version found: {0}\nCurrent version: {1}\n\nDo you want to update zapret strategies?',
        'update_available_text_app': 'New program version found: {0}\nCurrent version: {1}\n\nDo you want to update ZapretDeskop?',
        'update_error_title': 'Error',
        'update_error_url_not_found': 'Download URL not found',
        'update_stopping_winws': 'Stopping winws',
        'update_winws_running': 'Running winws.exe process detected',
        'update_winws_stop_required': 'The process must be stopped before updating. Stop now?',
        'update_title': 'Update',
        'update_downloading': 'Downloading update...',
        'update_installing': 'Installing update...',
        'update_completed': 'Update completed',
        'update_completed_text': 'Zapret strategies successfully updated to version {0}',
        'update_completed_text_app': 'ZapretDeskop successfully updated to version {0}',
        'update_restart_required': 'The program will restart automatically',
        'update_error_title': 'Update error',
        'update_error_text': 'Error updating: {0}',
        'update_manual_title': 'Update strategies',
        'update_manual_select_archive': 'Select archive for update',
        'update_manual_extracting': 'Extracting archive...',
        'update_manual_completed': 'Strategies successfully updated from archive',
        'addons_title': 'Add-ons',
        'addons_description': 'Links to repositories or GitHub releases to download lists and strategies.',
        'addons_col_name': 'Name',
        'addons_col_url': 'Link (repository or release)',
        'addons_download': 'Download',
        'addons_open_link': 'Open',
        'addons_add': 'Add',
        'addons_remove': 'Remove',
        'addons_save': 'Save',
        'addons_error_download': 'Error downloading: {0}',
        'addons_error_no_zip': 'No zip archive found in release',
        'addons_success': 'Add-on installed successfully',
        'addons_mode_label': 'Install mode',
        'addons_mode_full': 'Full install',
        'addons_mode_lists': 'Install lists (lists)',
        'addons_mode_strategies': 'Install strategies (winws)',
        'addons_mode_bin': 'Install binaries (bin)',
        'addons_search_placeholder': 'Search by name or link...',
        'addons_nothing_found': 'Nothing found',
        
        # Common for dialogs
        'msg_error': 'Error',
        'msg_information': 'Information',
        'msg_result': 'Result',
        'menu_create_strategy': 'Create Strategy',
        'msg_autostart_enable_failed': 'Failed to enable autostart',
        'msg_autostart_disable_failed': 'Failed to disable autostart',
        'msg_backup_not_found': 'Backup not found. Update IPSet list from update menu first.',
        'msg_backup_not_found_short': 'Backup not found. Update list from update menu first.',
        'msg_add_b_flag_title': 'Add /B flag',
        'msg_add_b_flag_text': 'Files to process: {0}\n\nIn all .bat files the line:\n{1}\nwill be replaced with:\n{2}\nContinue?',
        'msg_remove_b_flag_title': 'Remove /B flag',
        'msg_remove_b_flag_text': 'Files to process: {0}\n\nIn all .bat files the line:\n{1}\nwill be replaced with:\n{2}\nContinue?',
        'msg_processed_count': 'Files processed: {0}\nFiles modified: {1}',
        'msg_errors_section': 'Errors:\n',
        'export_menu_title': 'Export',
        'export_no_data': 'No data to export.',
        'export_table_empty': 'Table is empty. Nothing to export.',
        'export_column': 'Column {0}',
        'export_success': 'Data successfully exported to:\n{0}',
        'export_error_title': 'Export error',
        'export_error': 'Error exporting data:\n{0}',
        'msg_no_bat_to_process': 'No .bat files found to process',
        'msg_no_strategy_selected': 'No strategy selected for launch',
        'update_ipset_progress': 'Updating ipset-all...',
        'update_ipset_success': 'IPSet List updated successfully.',
        'update_ipset_error': 'Error updating IPSet List: {0}',
        'update_hosts_progress': 'Checking hosts file...',
        'update_hosts_needs_update': 'Hosts file needs to be updated. Please manually copy the content from the opened file to your hosts file.',
        'update_hosts_up_to_date': 'Hosts file is up to date.',
        'update_hosts_error': 'Error updating Hosts File: {0}',
        'update_hosts_download_failed': 'Failed to download hosts file from repository',
        'update_hosts_file_empty': 'Downloaded file is empty',
        'msg_game_filter_restart': 'Game Filter {0}. Restart zapret to apply changes.',
        'msg_game_filter_toggle_error': 'Error toggling Game Filter: {0}',
        'msg_ipset_filter_restart': 'IPSet Filter switched to {0} mode. Restart zapret to apply changes.',
        'msg_ipset_filter_toggle_error': 'Error toggling IPSet Filter: {0}',
        'msg_game_filter_enabled': 'enabled',
        'msg_game_filter_disabled': 'disabled',
        
        # Strategy creator
        'create_strategy_title': 'Create Strategy',
        'create_strategy_name_label': 'Strategy name:',
        'create_strategy_placeholder': 'general (CUSTOM)',
        'create_strategy_use_game_filter': 'Use Game Filter',
        'create_strategy_traffic_filters': 'Traffic Filters',
        'create_strategy_tcp_ports': 'TCP ports:',
        'create_strategy_udp_ports': 'UDP ports:',
        'create_strategy_l7_protocols': 'L7 protocols:',
        'create_strategy_l3_protocols': 'L3 protocols:',
        'create_strategy_tab_filters': 'Filters',
        'create_strategy_domain_lists': 'Domain Lists',
        'create_strategy_hostlist': 'Hostlist:',
        'create_strategy_hostlist_exclude': 'Hostlist exclude:',
        'create_strategy_hostlist_domains': 'Hostlist domains:',
        'create_strategy_tab_lists': 'Lists',
        'create_strategy_ipset_lists': 'IPSet Lists',
        'create_strategy_ipset': 'IPSet:',
        'create_strategy_ipset_exclude': 'IPSet exclude:',
        'create_strategy_dpi_methods': 'DPI Desync Methods',
        'create_strategy_dpi_desync': 'DPI Desync:',
        'create_strategy_repeats': 'Repeats:',
        'create_strategy_fake_quic': 'Fake QUIC:',
        'create_strategy_fake_tls': 'Fake TLS:',
        'create_strategy_fake_tls_mod': 'Fake TLS mod:',
        'create_strategy_fake_tls_placeholder': 'none or rnd,sni=www.google.com',
        'create_strategy_fooling': 'Fooling:',
        'create_strategy_split_seqovl': 'Split seqovl:',
        'create_strategy_split_pos': 'Split pos:',
        'create_strategy_split_pattern': 'Split pattern:',
        'create_strategy_autottl': 'AutoTTL:',
        'create_strategy_any_protocol': 'Any protocol:',
        'create_strategy_fake_unknown_udp': 'Fake unknown UDP:',
        'create_strategy_cutoff': 'Cutoff:',
        'create_strategy_tab_dpi': 'DPI Desync',
        'create_strategy_extra_params': 'Extra Parameters',
        'create_strategy_ip_id': 'IP ID:',
        'create_strategy_tab_extra': 'Extra',
        'create_strategy_btn': 'Create File',
        'msg_enter_strategy_name': 'Enter strategy name',
        'msg_fill_rule_field': 'Fill at least one rule field',
        'msg_confirm': 'Confirm',
        'msg_confirm_overwrite': 'Strategy "{0}" already exists. Overwrite?',
        'msg_success': 'Success',
        'msg_strategy_created': 'Strategy "{0}" created successfully',
        'msg_error_creating': 'Error creating strategy: {0}',
        'msg_file_not_found': 'File {0} not found at path: {1}',
        'msg_error_on_start': 'Error starting: {0}',
        'msg_error_on_stop': 'Error stopping process: {0}',
        'msg_error_launch_title': 'Launch error',
        'msg_winws_not_started': 'Strategy "{0}" did not start.\nwinws.exe process did not appear within 5 seconds.\n\nThe strategy may not work or may require additional configuration.',
        'msg_bat_path_not_allowed': 'Only .bat files from the winws folder are allowed to run.',
        'msg_bat_not_in_list': 'Strategy "{0}" is not in the allowed list. Refresh the strategies list.',
        
        # Diagnostics
        'diag_running': 'Running diagnostics...',
        'diag_completed': 'Diagnostics completed.',
        'export_txt': 'Export to TXT',
        'export_csv': 'Export to CSV',
        'export_json': 'Export to JSON',
        'diag_bfe_passed': 'Base Filtering Engine check passed',
        'diag_bfe_failed': '[X] Base Filtering Engine is not running. This service is required for zapret to work',
        'diag_error_bfe': 'Error checking BFE: {0}',
        'diag_proxy_enabled': '[?] System proxy is enabled: {0}',
        'diag_proxy_check_proxy': 'Make sure it\'s valid or disable it if you don\'t use a proxy',
        'diag_proxy_passed': 'Proxy check passed',
        'diag_error_proxy': 'Error checking proxy: {0}',
        'diag_tcp_passed': 'TCP timestamps check passed',
        'diag_tcp_disabled': '[?] TCP timestamps are disabled. Enabling timestamps...',
        'diag_tcp_enabled': 'TCP timestamps successfully enabled',
        'diag_tcp_failed': '[X] Failed to enable TCP timestamps',
        'diag_error_tcp': 'Error checking TCP timestamps: {0}',
        'diag_adguard_found': '[X] Adguard process found. Adguard may cause problems with Discord',
        'diag_adguard_passed': 'Adguard check passed',
        'diag_killer_found': '[X] Killer services found. Killer conflicts with zapret',
        'diag_killer_passed': 'Killer check passed',
        'diag_error_killer': 'Error checking Killer services: {0}',
        'diag_intel_found': '[X] Intel Connectivity Network Service found. It conflicts with zapret',
        'diag_intel_passed': 'Intel Connectivity check passed',
        'diag_error_intel': 'Error checking Intel Connectivity: {0}',
        'diag_checkpoint_found': '[X] Check Point services found. Check Point conflicts with zapret',
        'diag_checkpoint_uninstall': 'Try to uninstall Check Point',
        'diag_checkpoint_passed': 'Check Point check passed',
        'diag_error_checkpoint': 'Error checking Check Point: {0}',
        'diag_smartbyte_found': '[X] SmartByte services found. SmartByte conflicts with zapret',
        'diag_smartbyte_uninstall': 'Try to uninstall or disable SmartByte through services.msc',
        'diag_smartbyte_passed': 'SmartByte check passed',
        'diag_error_smartbyte': 'Error checking SmartByte: {0}',
        'diag_windivert_not_found': 'WinDivert64.sys file NOT found.',
        'diag_windivert_found': 'WinDivert64.sys file found: {0}',
        'diag_error_windivert': 'Error checking WinDivert64.sys: {0}',
        'diag_vpn_found': '[?] VPN services found: {0}. Some VPNs can conflict with zapret',
        'diag_vpn_disable': 'Make sure that all VPNs are disabled',
        'diag_vpn_passed': 'VPN check passed',
        'diag_error_vpn': 'Error checking VPN services: {0}',
        'diag_dns_configure': '[?] Make sure you have configured secure DNS in a browser with some non-default DNS service provider,',
        'diag_dns_win11': 'If you use Windows 11 you can configure encrypted DNS in the Settings to hide this warning',
        'diag_secure_dns_passed': 'Secure DNS check passed',
        'diag_dns_unknown': '[?] Could not check secure DNS configuration',
        'diag_windivert_attempt': '[?] winws.exe is not running but WinDivert service is active. Attempting to delete WinDivert...',
        'diag_windivert_removed': 'WinDivert successfully removed',
        'diag_windivert_delete_failed': '[X] Failed to delete WinDivert. Check manually if any other bypass is using WinDivert.',
        'diag_windivert_error': '[X] Error removing WinDivert: {0}',
        'diag_windivert_conflict_passed': 'WinDivert conflict check passed',
        'diag_error_windivert_conflict': 'Error checking WinDivert conflict: {0}',
        'diag_zapret_running': 'Zapret service is running',
        'diag_zapret_strategy': 'Service strategy: {0}',
        'diag_zapret_stopped': '[?] Zapret service is installed but not running',
        'diag_zapret_unknown': '[?] Zapret service status unknown',
        'diag_zapret_not_installed': '[?] Zapret service is not installed',
        'diag_error_zapret': 'Error checking zapret service: {0}',
        'diag_winws_running': 'winws.exe is running (PID: {0})',
        'diag_winws_not_running': '[?] winws.exe is not running',
        'diag_error_winws': 'Error checking winws.exe: {0}',
        'diag_windows_version': 'Windows {0} (Build {1}, {2})',
        'diag_error_windows': 'Error checking Windows version: {0}',
        'diag_admin_yes': 'Running with administrator privileges',
        'diag_admin_no': '[X] Not running with administrator privileges. Some features may not work',
        'diag_error_admin': 'Error checking admin privileges: {0}',
        'diag_strategies_found': 'Found {0} strategy file(s)',
        'diag_strategies_empty': '[?] No strategy files found in strategies folder',
        'diag_strategies_not_found': '[?] Strategies folder not found',
        'diag_error_strategies': 'Error checking strategies: {0}',
        'diag_dns_servers': 'DNS servers configured: {0}',
        'diag_dns_not_detected': '[?] Could not detect DNS servers',
        'diag_error_dns': 'Error checking DNS servers: {0}',
        'diag_adapters_found': 'Found {0} network adapter(s)',
        'diag_adapters_not_detected': '[?] Could not detect network adapters',
        'diag_error_adapters': 'Error checking network adapters: {0}',
        'diag_targets_found': 'targets.txt found with {0} target(s)',
        'diag_targets_not_found': '[?] targets.txt not found',
        'diag_error_targets': 'Error checking targets.txt: {0}',
        'diag_hosts_found': 'hosts file found with {0} entry/entries',
        'diag_hosts_not_found': '[X] hosts file not found',
        'diag_error_hosts': 'Error checking hosts file: {0}',
    }
}


def tr(key: str, language: str = 'ru') -> str:
    """
    Получает перевод строки по ключу и языку
    
    Args:
        key: Ключ перевода
        language: Язык ('ru' или 'en')
    
    Returns:
        Переведенная строка или ключ, если перевод не найден
    """
    return TRANSLATIONS.get(language, TRANSLATIONS['ru']).get(key, key)

